name: Moodle Accessibility Text Colour Widget Releasing

on:
  push:
    branches:
      - master

jobs:

  release:
    name: Release

    runs-on: ubuntu-latest

    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions:
          ini-values: max_input_vars=5000
          coverage: none

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Get Plugin Information
        id: plugin-info
        run: php -r 'define("MOODLE_INTERNAL",1);define("MATURITY_ALPHA",50);define("MATURITY_BETA",100);define("MATURITY_RC",150);define("MATURITY_STABLE",200);define("ANY_VERSION","any");$plugin=new stdClass();include_once("version.php");$plugin->maturity!=200&&throw new Exception("Requires plugin maturity to be stable to release!");echo "PLUGIN_COMPONENT=".(isset($plugin->component)?$plugin->component:"")."\nPLUGIN_RELEASE=".(isset($plugin->release)?$plugin->release:"")."\nPLUGIN_VERSION=".(isset($plugin->version)?$plugin->version:"")."\nPLUGIN_REQUIRES=".(isset($plugin->requires)?$plugin->requires:"")."\nPLUGIN_MATURITY=".(isset($plugin->maturity)?$plugin->maturity:"")."\nPLUGIN_DEPENDENCIES=".(isset($plugin->dependencies)?json_encode($plugin->dependencies):"{}");' >> $GITHUB_OUTPUT

      - name: Get Branch Name
        id: get-branch
        run: php -r 'echo "BRANCH_NAME=".preg_replace("/(\\(|\\))/", "", strtolower(str_replace(" ", "-", preg_replace("/(\\d+)\\.(\\d+)\\.(\\d+)(.*)/","v$1.$2$4", "${{ steps.plugin-info.outputs.PLUGIN_RELEASE }}"))));'  >> $GITHUB_OUTPUT

      - name: Push to Branch
        run: |
          git checkout -b ${{ steps.get-branch.outputs.BRANCH_NAME }}
          git push -f -u origin ${{ steps.get-branch.outputs.BRANCH_NAME }}

      - name: Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{ steps.plugin-info.outputs.PLUGIN_RELEASE }}
          release_branches: ${{ github.ref_name }}

      - name: Relase
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.plugin-info.outputs.PLUGIN_RELEASE }}
          body: ${{ steps.plugin-info.outputs.PLUGIN_RELEASE }} - ${{ steps.plugin-info.outputs.PLUGIN_VERSION }}
